# Generated by Django 4.2.4 on 2023-08-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Natural', 'Natural'), ('Jurídico', 'Jurídico')], max_length=10)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'Número de identificación tributaria'), ('TI', 'Tarjeta de Identidad')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_direccion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Urbano', 'Urbano'), ('Rural', 'Rural')], max_length=10)),
                ('numero_catastral', models.CharField(max_length=30, unique=True)),
                ('numero_matricula', models.CharField(max_length=30, unique=True)),
                ('propietarios', models.ManyToManyField(to='predios.propietario')),
            ],
        ),
    ]
