# Generated by Django 4.2.4 on 2023-08-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predio',
            old_name='nombre_direccion',
            new_name='nombre_o_Direccion',
        ),
    ]
