# Generated by Django 4.2.4 on 2023-08-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predios', '0002_rename_nombre_direccion_predio_nombre_o_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predio',
            old_name='tipo',
            new_name='tipo_predio',
        ),
        migrations.RenameField(
            model_name='propietario',
            old_name='tipo',
            new_name='tipo_propietario',
        ),
        migrations.AlterField(
            model_name='predio',
            name='propietarios',
            field=models.ManyToManyField(related_name='predios', to='predios.propietario'),
        ),
    ]
